-- Add 100 movies to the movies table
INSERT INTO movies (title, description, duration, price, release_date) VALUES
('Inception', 'A thief who steals corporate secrets through the use of dream-sharing technology', 148, 12.99, '2010-07-16'),
('The Shawshank Redemption', 'Two imprisoned men bond over a number of years', 142, 11.99, '1994-09-23'),
('The Dark Knight', 'Batman fights the menace known as The Joker', 152, 13.99, '2008-07-18'),
('Pulp Fiction', 'The lives of two mob hitmen, a boxer, and a gangster''s wife converge', 154, 10.99, '1994-10-14'),
('Fight Club', 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club', 139, 11.99, '1999-10-15'),
('Forrest Gump', 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold through the perspective of an Alabama man', 142, 10.99, '1994-07-06'),
('The Matrix', 'A computer hacker learns about the true nature of reality', 136, 12.99, '1999-03-31'),
('Goodfellas', 'The story of Henry Hill and his life in the mob', 146, 10.99, '1990-09-19'),
('The Silence of the Lambs', 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer', 118, 9.99, '1991-02-14'),
('Saving Private Ryan', 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines', 169, 13.99, '1998-07-24'),
('Interstellar', 'A team of explorers travel through a wormhole in space', 169, 14.99, '2014-11-07'),
('The Green Mile', 'The lives of guards on Death Row are affected by one of their charges', 189, 10.99, '1999-12-10'),
('Star Wars: Episode IV', 'Luke Skywalker joins forces with a Jedi Knight', 121, 12.99, '1977-05-25'),
('The Godfather', 'The aging patriarch of an organized crime dynasty transfers control to his son', 175, 11.99, '1972-03-24'),
('The Godfather: Part II', 'The early life and career of Vito Corleone in 1920s New York', 202, 11.99, '1974-12-20'),
('The Lord of the Rings: The Fellowship of the Ring', 'A meek Hobbit and eight companions set out on a journey', 178, 13.99, '2001-12-19'),
('The Lord of the Rings: The Two Towers', 'While Frodo and Sam edge closer to Mordor, the divided fellowship makes a stand against Sauron''s forces', 179, 13.99, '2002-12-18'),
('The Lord of the Rings: The Return of the King', 'Gandalf and Aragorn lead the World of Men against Sauron''s army', 201, 13.99, '2003-12-17'),
('Schindler''s List', 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce', 195, 10.99, '1993-12-15'),
('Gladiator', 'A former Roman General sets out to exact vengeance against the corrupt emperor', 155, 11.99, '2000-05-05'),
('Titanic', 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic', 194, 12.99, '1997-12-19'),
('Jurassic Park', 'A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids', 127, 10.99, '1993-06-11'),
('The Avengers', 'Earth''s mightiest heroes must come together and learn to fight as a team', 143, 13.99, '2012-05-04'),
('Avengers: Infinity War', 'The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos', 149, 14.99, '2018-04-27'),
('Avengers: Endgame', 'After the devastating events of Infinity War, the universe is in ruins', 181, 14.99, '2019-04-26'),
('The Wolf of Wall Street', 'Based on the true story of Jordan Belfort', 180, 12.99, '2013-12-25'),
('Inglourious Basterds', 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers', 153, 11.99, '2009-08-21'),
('Eternal Sunshine of the Spotless Mind', 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories', 108, 10.99, '2004-03-19'),
('The Departed', 'An undercover cop and a mole in the police attempt to identify each other', 151, 11.99, '2006-10-06'),
('The Prestige', 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion', 130, 11.99, '2006-10-20'),
('The Social Network', 'Harvard student Mark Zuckerberg creates Facebook', 120, 10.99, '2010-10-01'),
('The Revenant', 'A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear', 156, 12.99, '2015-12-25'),
('Django Unchained', 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner', 165, 11.99, '2012-12-25'),
('Whiplash', 'A promising young drummer enrolls at a cut-throat music conservatory', 107, 9.99, '2014-10-10'),
('The Dark Knight Rises', 'Eight years after the Joker''s reign of anarchy, Batman must return to save Gotham City', 165, 13.99, '2012-07-20'),
('Mad Max: Fury Road', 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland', 120, 12.99, '2015-05-15'),
('Parasite', 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan', 132, 14.99, '2019-11-08'),
('Joker', 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society', 122, 14.99, '2019-10-04'),
('Back to the Future', 'Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past', 116, 10.99, '1985-07-03'),
('Coco', 'Aspiring musician Miguel, confronted with his family''s ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather', 105, 12.99, '2017-11-22'),
('La La Land', 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future', 128, 11.99, '2016-12-09'),
('Spider-Man: Into the Spider-Verse', 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five counterparts from other dimensions to stop a threat for all realities', 117, 13.99, '2018-12-14'),
('Harry Potter and the Sorcerer''s Stone', 'An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family and the terrible evil that haunts the magical world', 152, 11.99, '2001-11-16'),
('Harry Potter and the Chamber of Secrets', 'Harry ignores warnings not to return to Hogwarts when students are attacked', 161, 11.99, '2002-11-15'),
('Harry Potter and the Prisoner of Azkaban', 'Harry Potter, Ron and Hermione return to Hogwarts School of Witchcraft and Wizardry for their third year of study', 142, 11.99, '2004-06-04'),
('Harry Potter and the Goblet of Fire', 'Harry Potter finds himself competing in a hazardous tournament between rival schools of magic', 157, 11.99, '2005-11-18'),
('Harry Potter and the Order of the Phoenix', 'With their warning about Lord Voldemort''s return scoffed at, Harry and Dumbledore are targeted by the Wizard authorities', 138, 11.99, '2007-07-11'),
('Harry Potter and the Half-Blood Prince', 'As Harry Potter begins his sixth year at Hogwarts, he discovers an old book marked as the property of the Half-Blood Prince', 153, 11.99, '2009-07-15'),
('Harry Potter and the Deathly Hallows – Part 1', 'As Harry, Ron, and Hermione race against time and evil to destroy the Horcruxes, they uncover the existence of the three most powerful objects in the wizarding world', 146, 12.99, '2010-11-19'),
('Harry Potter and the Deathly Hallows – Part 2', 'Harry, Ron, and Hermione search for Voldemort''s remaining Horcruxes in their effort to destroy the Dark Lord', 130, 12.99, '2011-07-15'),
('The Lion King', 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself', 88, 10.99, '1994-06-24'),
('Toy Story', 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy''s room', 81, 9.99, '1995-11-22'),
('Toy Story 2', 'When Woody is stolen by a toy collector, Buzz and his friends set out on a rescue mission to save Woody', 92, 9.99, '1999-11-24'),
('Toy Story 3', 'The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college', 103, 10.99, '2010-06-18'),
('Toy Story 4', 'When a new toy called "Forky" joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy', 100, 12.99, '2019-06-21'),
('Finding Nemo', 'After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home', 100, 10.99, '2003-05-30'),
('Finding Dory', 'The friendly but forgetful blue tang fish, Dory, begins a search for her long-lost parents', 97, 12.99, '2016-06-17'),
('Up', '78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway', 96, 10.99, '2009-05-29'),
('Inside Out', 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school', 95, 11.99, '2015-06-19'),
('The Incredibles', 'A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world', 115, 10.99, '2004-11-05'),
('Incredibles 2', 'The Incredibles hero family takes on a new mission, which involves a change in family roles', 118, 12.99, '2018-06-15'),
('WALL·E', 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind', 98, 10.99, '2008-06-27'),
('Ratatouille', 'A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant', 111, 10.99, '2007-06-29'),
('Monsters, Inc.', 'In order to power the city, monsters have to scare children so that they scream', 92, 9.99, '2001-11-02'),
('Monsters University', 'A look at the relationship between Mike Wazowski and James P. "Sully" Sullivan during their days at Monsters University', 104, 11.99, '2013-06-21'),
('The Hunger Games', 'Katniss Everdeen voluntarily takes her younger sister''s place in the Hunger Games', 142, 11.99, '2012-03-23'),
('The Hunger Games: Catching Fire', 'Katniss Everdeen and Peeta Mellark become targets of the Capitol after their victory in the 74th Hunger Games sparks a rebellion', 146, 11.99, '2013-11-22'),
('The Hunger Games: Mockingjay – Part 1', 'Katniss Everdeen is in District 13 after she shatters the games forever', 123, 11.99, '2014-11-21'),
('The Hunger Games: Mockingjay – Part 2', 'As the war of Panem escalates to the destruction of other districts, Katniss Everdeen must decide for herself who she can trust', 137, 12.99, '2015-11-20'),
('Iron Man', 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil', 126, 10.99, '2008-05-02'),
('Thor', 'The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard (Earth)', 115, 10.99, '2011-05-06'),
('Captain America: The First Avenger', 'Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a "Super-Soldier serum"', 124, 10.99, '2011-07-22'),
('Guardians of the Galaxy', 'A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe', 121, 11.99, '2014-08-01'),
('Black Panther', 'T''Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future', 134, 13.99, '2018-02-16'),
('Captain Marvel', 'Carol Danvers becomes one of the universe''s most powerful heroes when Earth is caught in the middle of a galactic war', 123, 13.99, '2019-03-08'),
('Doctor Strange', 'While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts', 115, 12.99, '2016-11-04'),
('Deadpool', 'A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks', 108, 11.99, '2016-02-12'),
('Logan', 'In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life', 137, 12.99, '2017-03-03'),
('Wonder Woman', 'When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight', 141, 12.99, '2017-06-02'),
('Aquaman', 'Arthur Curry, the human-born heir to the underwater kingdom of Atlantis, goes on a quest to prevent a war between the worlds of ocean and land', 143, 13.99, '2018-12-21'),
('Shazam!', 'A newly fostered young boy in search of his mother instead finds unexpected super powers', 132, 13.99, '2019-04-05'),
('Spider-Man: Homecoming', 'Peter Parker balances his life as an ordinary high school student in Queens with his superhero alter-ego Spider-Man', 133, 12.99, '2017-07-07'),
('Spider-Man: Far From Home', 'Following the events of Avengers: Endgame, Spider-Man must step up to take on new threats in a world that has changed forever', 129, 13.99, '2019-07-02'),
('Ant-Man', 'Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero', 117, 11.99, '2015-07-17'),
('Ant-Man and the Wasp', 'As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission', 118, 12.99, '2018-07-06'),
('Venom', 'A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth', 112, 12.99, '2018-10-05'),
('Get Out', 'A young African-American visits his white girlfriend''s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point', 104, 11.99, '2017-02-24'),
('A Quiet Place', 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing', 90, 12.99, '2018-04-06'),
('Bird Box', 'Five years after an ominous unseen presence drives most of society to suicide, a survivor and her two children make a desperate bid to reach safety', 124, 12.99, '2018-12-21'),
('Us', 'A family''s serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them', 116, 13.99, '2019-03-22'),
('IT', 'In the summer of 1989, a group of bullied kids band together to destroy a shape-shifting monster', 135, 12.99, '2017-09-08'),
('IT Chapter Two', '27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers'' Club, reunite', 169, 13.99, '2019-09-06'),
('Hereditary', 'A grieving family is haunted by tragic and disturbing occurrences', 127, 12.99, '2018-06-08'),
('The Conjuring', 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse', 112, 10.99, '2013-07-19'),
('Annabelle', 'A couple begins to experience terrifying supernatural occurrences involving a vintage doll', 99, 10.99, '2014-10-03'),
('The Witch', 'A family in 1630s New England is torn apart by the forces of witchcraft', 92, 10.99, '2016-02-19'); 